// <auto-generated />
using System;
using ExpenseGuard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseGuard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005093740_ConsolidatedMergedSchema")]
    partial class ConsolidatedMergedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalProcess", b =>
                {
                    b.Property<Guid>("ApprovalProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalWorkflowTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("integer");

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalProcessId");

                    b.HasIndex("ApprovalWorkflowTemplateId");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("ApprovalProcesses");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStageDefinition", b =>
                {
                    b.Property<int>("ApprovalStageDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalStageDefinitionId"));

                    b.Property<int>("ApprovalWorkflowTemplateId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaximumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("ApprovalStageDefinitionId");

                    b.HasIndex("ApprovalWorkflowTemplateId", "Sequence")
                        .IsUnique();

                    b.ToTable("ApprovalStageDefinitions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStep", b =>
                {
                    b.Property<Guid>("ApprovalStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DecidedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("StageSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalStepId");

                    b.HasIndex("DecidedByEmployeeId");

                    b.HasIndex("ApprovalProcessId", "Sequence")
                        .IsUnique();

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", b =>
                {
                    b.Property<int>("ApprovalWorkflowTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApprovalWorkflowTemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalWorkflowTemplateId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ApprovalWorkflowTemplates");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuditLogId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetId"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("ReservedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("BudgetId");

                    b.HasIndex("DepartmentId", "PeriodStart", "PeriodEnd", "Currency")
                        .IsUnique();

                    b.ToTable("Budgets", t =>
                        {
                            t.HasCheckConstraint("CK_Budgets_Balances", "\"AllocatedAmount\" >= 0 AND \"ReservedAmount\" >= 0 AND \"SpentAmount\" >= 0 AND \"ReservedAmount\" + \"SpentAmount\" <= \"AllocatedAmount\"");

                            t.HasCheckConstraint("CK_Budgets_Dates", "\"PeriodEnd\" >= \"PeriodStart\"");
                        });
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.BudgetAlert", b =>
                {
                    b.Property<long>("BudgetAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BudgetAlertId"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("UtilizationPercent")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("BudgetAlertId");

                    b.HasIndex("BudgetId", "ThresholdPercent", "Status");

                    b.ToTable("BudgetAlerts");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.BudgetTransaction", b =>
                {
                    b.Property<long>("BudgetTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BudgetTransactionId"));

                    b.Property<decimal>("AllocatedBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ReservedBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SpentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("BudgetTransactionId");

                    b.HasIndex("BudgetId", "CreatedAt");

                    b.HasIndex("BudgetId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.ToTable("BudgetTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetTransactions_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ClaimStatusHistory", b =>
                {
                    b.Property<int>("ClaimStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClaimStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("ClaimStatusHistoryId");

                    b.HasIndex("ExpenseClaimId");

                    b.ToTable("ClaimStatusHistories");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DesignationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DesignationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ExpenseClaim", b =>
                {
                    b.Property<int>("ExpenseClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenseClaimId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PurchaseRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptDoc")
                        .HasColumnType("text");

                    b.Property<string>("ReceiptImg")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ExpenseClaimId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("Status");

                    b.ToTable("ExpenseClaims");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudEvaluation", b =>
                {
                    b.Property<int>("FraudEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FraudEvaluationId"));

                    b.Property<decimal>("ClaimAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ReceiptAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("FraudEvaluationId");

                    b.HasIndex("NormalizedInvoiceNumber");

                    b.HasIndex("ExpenseClaimId", "InputFingerprint")
                        .IsUnique();

                    b.ToTable("FraudEvaluations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudFlag", b =>
                {
                    b.Property<int>("FraudFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FraudFlagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("FlagReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FraudEvaluationId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("RiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("FraudFlagId");

                    b.HasIndex("ExpenseClaimId");

                    b.HasIndex("FraudEvaluationId");

                    b.HasIndex("Status", "Severity", "CreatedAt");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReimbursementId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReimbursementId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("ReceiptRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("PolicyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PolicyCode", "Version")
                        .IsUnique();

                    b.HasIndex("IsActive", "Category", "Currency", "DepartmentId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyDesignation", b =>
                {
                    b.Property<int>("PolicyDesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyDesignationId"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("integer");

                    b.HasKey("PolicyDesignationId");

                    b.HasIndex("PolicyId", "Designation")
                        .IsUnique();

                    b.ToTable("PolicyDesignations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyEvaluation", b =>
                {
                    b.Property<int>("PolicyEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyEvaluationId"));

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("integer");

                    b.HasKey("PolicyEvaluationId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ExpenseClaimId", "InputFingerprint")
                        .IsUnique();

                    b.ToTable("PolicyEvaluations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyViolation", b =>
                {
                    b.Property<int>("PolicyViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyViolationId"));

                    b.Property<decimal?>("ActualAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PolicyEvaluationId")
                        .HasColumnType("integer");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PolicyViolationId");

                    b.HasIndex("PolicyEvaluationId");

                    b.ToTable("PolicyViolations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("PurchaseRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PurchaseRequestId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReceiptId"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CorrectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CorrectedByEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ExtractedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ExtractedCurrency")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExtractedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedVendor")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReceiptId");

                    b.HasIndex("ExpenseClaimId", "Sha256")
                        .IsUnique();

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Reimbursement", b =>
                {
                    b.Property<int>("ReimbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReimbursementId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("text");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReimbursementId");

                    b.HasIndex("ExpenseClaimId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Reimbursements");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<decimal>("ApprovalLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanProcessPayments")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ApprovalLimit = 0m,
                            CanApprove = false,
                            CanManageRoles = false,
                            CanProcessPayments = false,
                            PermissionsJson = "[\"reimbursement:self\"]",
                            RoleName = "Employee"
                        },
                        new
                        {
                            RoleId = 2,
                            ApprovalLimit = 100000m,
                            CanApprove = true,
                            CanManageRoles = false,
                            CanProcessPayments = false,
                            PermissionsJson = "[\"reimbursement:approve\"]",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            ApprovalLimit = 1000000m,
                            CanApprove = true,
                            CanManageRoles = false,
                            CanProcessPayments = false,
                            PermissionsJson = "[\"reimbursement:approve\"]",
                            RoleName = "DepartmentHead"
                        },
                        new
                        {
                            RoleId = 4,
                            ApprovalLimit = 0m,
                            CanApprove = false,
                            CanManageRoles = false,
                            CanProcessPayments = true,
                            PermissionsJson = "[\"payment:process\"]",
                            RoleName = "Finance"
                        },
                        new
                        {
                            RoleId = 5,
                            ApprovalLimit = 9999999999999999.99m,
                            CanApprove = true,
                            CanManageRoles = true,
                            CanProcessPayments = true,
                            PermissionsJson = "[\"*\"]",
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ToolExecution", b =>
                {
                    b.Property<Guid>("ToolExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.HasKey("ToolExecutionId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("ToolExecutions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ValidationResult", b =>
                {
                    b.Property<Guid>("ValidationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Validator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid");

                    b.HasKey("ValidationResultId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("ValidationResults");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowExecution", b =>
                {
                    b.Property<Guid>("WorkflowExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WorkflowExecutionId");

                    b.HasIndex("ExpenseClaimId");

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("WorkflowStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputSnapshotJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputSnapshotJson")
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkflowStepId");

                    b.HasIndex("WorkflowExecutionId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalProcess", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("ApprovalWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("ApprovalProcesses")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reimbursement");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStageDefinition", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", "Template")
                        .WithMany("Stages")
                        .HasForeignKey("ApprovalWorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalStep", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ApprovalProcess", "ApprovalProcess")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Employee", "DecidedByEmployee")
                        .WithMany()
                        .HasForeignKey("DecidedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovalProcess");

                    b.Navigation("DecidedByEmployee");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.AuditLog", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Budget", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany("Budgets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.BudgetAlert", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Budget", "Budget")
                        .WithMany("Alerts")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.BudgetTransaction", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Budget", "Budget")
                        .WithMany("Transactions")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ClaimStatusHistory", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Employee", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ExpenseGuard.Api.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ExpenseClaim", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Employee")
                        .WithMany("ExpenseClaims")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Claims")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudEvaluation", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany("FraudEvaluations")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudFlag", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany("FraudFlags")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.FraudEvaluation", "FraudEvaluation")
                        .WithMany("Flags")
                        .HasForeignKey("FraudEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExpenseClaim");

                    b.Navigation("FraudEvaluation");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PaymentTransaction", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Policy", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Department", "Department")
                        .WithMany("Policies")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyDesignation", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Policy", "Policy")
                        .WithMany("Designations")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyEvaluation", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany("PolicyEvaluations")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseGuard.Api.Models.Policy", "Policy")
                        .WithMany("Evaluations")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExpenseClaim");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyViolation", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.PolicyEvaluation", "PolicyEvaluation")
                        .WithMany("Violations")
                        .HasForeignKey("PolicyEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyEvaluation");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PurchaseRequest", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.Employee", "Employee")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Receipt", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany("Receipts")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Reimbursement", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithOne("Reimbursement")
                        .HasForeignKey("ExpenseGuard.Api.Models.Reimbursement", "ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ToolExecution", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("ToolExecutions")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ValidationResult", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.WorkflowStep", "WorkflowStep")
                        .WithMany("ValidationResults")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowExecution", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.ExpenseClaim", "ExpenseClaim")
                        .WithMany()
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowStep", b =>
                {
                    b.HasOne("ExpenseGuard.Api.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalProcess", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ApprovalWorkflowTemplate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Budget", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Department", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Employees");

                    b.Navigation("Policies");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("ExpenseClaims");

                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.ExpenseClaim", b =>
                {
                    b.Navigation("FraudEvaluations");

                    b.Navigation("FraudFlags");

                    b.Navigation("PolicyEvaluations");

                    b.Navigation("Receipts");

                    b.Navigation("Reimbursement");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.FraudEvaluation", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Policy", b =>
                {
                    b.Navigation("Designations");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PolicyEvaluation", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.PurchaseRequest", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Reimbursement", b =>
                {
                    b.Navigation("ApprovalProcesses");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowExecution", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ExpenseGuard.Api.Models.WorkflowStep", b =>
                {
                    b.Navigation("ToolExecutions");

                    b.Navigation("ValidationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
